# set this variable to false to force Travis to build our app inside of a docker container!
sudo: false
language: node_js
node_js:
  - "6.10.0"
notifications:
  slack:
   rooms:
     - storied:G6gGMIpNuBpSUOKnTH2XBd6Z#travis
   on_success: always
   on_failure: always
   on_start: always
# node_modules can be cached inbetween builds
cache:
  directories:
    - node_modules

# whitelist of branches that will trigger a build
branches:
  only:
    - development
    - master

# Build the application
install:
  - npm set progress=false
  - npm install --no-optional
  - npm run lint
  - npm run build

# Zip the application up before deploying it to S3
before_deploy:
  - zip -r -q -T latest . && echo "ZIP Created." || echo "Error creating ZIP."
  - mkdir -p upload
  - mv latest.zip upload/${TRAVIS_COMMIT}.zip

# The first deploy step is uploading the build to builds.storied.co
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAI2PZCTXIEEZW3SRA
    secret_access_key: ShAPmO1vCyzainleaEKreR7ON9+Kt+NQwaO9kTDZ
    local_dir: upload
    wait-until-deployed: true
    bucket: builds.storied.co
    upload-dir:  YOUR_APP_NAME
    region: us-west-1
    on:
      all_branches: true


# Finally , tell AWS CodeDeploy to deploy the ZIP to our fleet of servers.
# Deployment settings for staging.
  - provider: codedeploy
    access_key_id: AKIAI2PZCTXIEEZW3SRA
    secret_access_key: ShAPmO1vCyzainleaEKreR7ON9+Kt+NQwaO9kTDZ
    bucket: builds.storied.co
    key:  YOUR_APP_NAME/${TRAVIS_COMMIT}.zip
    region: us-west-1
    application: YOUR_APP_NAME
    deployment_group: stage
    wait-until-deployed: true
    bundle_type: zip
    on:
      branch: development
# Deployment settings for production.
  - provider: codedeploy
    access_key_id: AKIAI2PZCTXIEEZW3SRA
    secret_access_key: ShAPmO1vCyzainleaEKreR7ON9+Kt+NQwaO9kTDZ
    bucket: builds.storied.co
    key:  YOUR_APP_NAME/${TRAVIS_COMMIT}.zip
    region: us-west-1
    application: YOUR_APP_NAME
    deployment_group: production
    wait-until-deployed: true
    bundle_type: zip
    on:
      branch: master
